version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports: 
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: siddik/selenium-docker
    depends_on:
        - chrome
        - firefox
    environment: 
        - BROWSER=firefox
        - HUB_HOST=hub
        - MODULE=search-module.xml
    volumes: 
        - ./output/search-results:/usr/share/udemy/test-output
  book-flight-module:
    image: siddik/selenium-docker
    depends_on:
        - chrome
        - firefox
    environment: 
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=book-flight-module.xml
    volumes: 
        - ./output/book-results:/usr/share/udemy/test-output